# Config file for automatic testing at travis-ci.org

branches:
  # Exclude some branches (which names start with branch2go or underscore) from travis
  except:
    - /^(?i:branch2go)-.*$/
    - /^(_)-.*$/
    - /^(_{1}\w)/

language: python

python:
  - "3.5"

install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION --file requirements.txt
  - source activate test-environment
  - python setup.py install
  - pip install codecov

before_script:
  # Start x virtual framebuffer for gui
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  - coverage run --omit=tests/*,setup.py setup.py test

after_success:
  - codecov
